### ISSUE TITLE
npm install fails on node16?

### ISSUE THREAD

**Issue by leonardlin** [komodojp/tinyld#10]
Running: npm install

Fails with error:
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp -- install --update-binary --fallback-to-build=false || npm run build -- --release
npm ERR! 403 status code downloading tarball https://x-tech-npm-binaries.s3-us-west-2.amazonaws.com/lingua-node/v0.3.0/Release/lingua-node-linux-x64-node-v93.tar.gz
npm ERR! 
npm ERR! > lingua-node@0.3.0 build
npm ERR! > neon build "--release"
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.17.0
npm ERR! node-pre-gyp info using node@16.13.1 | linux | x64
npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "/home/leonard/workspace/tinyld/node_modules/lingua-node/native/index.node" (not found)
npm ERR! node-pre-gyp http GET https://x-tech-npm-binaries.s3-us-west-2.amazonaws.com/lingua-node/v0.3.0/Release/lingua-node-linux-x64-node-v93.tar.gz
npm ERR! node-pre-gyp http 403 https://x-tech-npm-binaries.s3-us-west-2.amazonaws.com/lingua-node/v0.3.0/Release/lingua-node-linux-x64-node-v93.tar.gz
npm ERR! node-pre-gyp ERR! install error 
npm ERR! node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://x-tech-npm-binaries.s3-us-west-2.amazonaws.com/lingua-node/v0.3.0/Release/lingua-node-linux-x64-node-v93.tar.gz

https://github.com/botisan-ai/lingua-node

has new version addressing build failure on node16.

I try to upgrade and will create a PR if successful.

**Comment by kefniark** [comment]
ha yes, I noticed that recently, the `dev-dependencies` only install <= node14
the benchmark process is the culprit (and the need to install bunch of other third party libs to test them)
Some of them have native dependencies and can cause lot of install problems.

I already created an issue for that, the idea is to move that benchmarking process and those dependencies into a dedicated sub project and dockerize it. But I have started to work on it yet https://github.com/komodojp/tinyld/issues/6
One of the workaround for the moment is to manually remove problematic dependencies from package.json
```
"cld": "^2.7.0",
"lingua-node": "^0.3.0",
```
It should install and you should be able to run normal commands like `yarn test`, `yarn build`.

I will double check the `0.4.1` version of `lingua-node` to see if it solve the install problem on node 16

**Comment by kefniark** [comment]
Indeed I confirm that after upgrading to `lingua-node@0.4.1`, it install on node16.
Updated that 👍

**Comment by leonardlin** [comment]
I just went out for grocery shopping, but it seems you fixed it all already.
