### ISSUE TITLE
File missing in the 1.3.2 release

### ISSUE THREAD

**Issue by LinaKind** [komodojp/tinyld#21]
Unable to use the most recent release due to below error: 

> npm i tinyld@latest

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path [...]/node_modules/tinyld/bin/tinyld-heavy.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '[...]/node_modules/tinyld/bin/tinyld-heavy.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by kefniark** [comment]
Ho thanks, indeed something looks wrong, it indeed looks like one of the `/bin` script was not renamed properly.

Just to know what version of npm are you using?
I just would like to reproduce the issue to be sure my fix works properly.

For me both npm & yarn have no trouble with it. They don't even show a warning
```sh
$ yarn add tinyld
yarn add v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ tinyld@1.3.2
info All dependencies
└─ tinyld@1.3.2
Done in 44.73s.
```

```sh
$ npm i tinyld@latest

added 1 package, and audited 2 packages in 2s

found 0 vulnerabilities
```

**Comment by kefniark** [comment]
I published https://www.npmjs.com/package/tinyld/v/1.3.3
Let me know if it solve your problem

**Comment by LinaKind** [comment]
That solves the problem. Thank you!
