### ISSUE TITLE
tinyld/light work awful

### ISSUE THREAD

**Issue by NullVerdict** [komodojp/tinyld#24]
tinyld/light was trained very badly, it sees Hungarian in English text, Russian in English, etc. Please retrain him.

**Comment by kefniark** [comment]
Thanks for opening an issue here, sadly I don't think I can help you.

"It doesn't work as I expect" is not a constructive comment and it's really hard for me to make any change or improvement based on such fuzzy feedback. I have absolutely no context on what you are trying to achieve, and how you are using this library.
All I can guess is that you are probably not using the right tool for the right task.
I really don't see what I can do for you here, so I will just close this issue for the moment.

Feel free to open another issue later, and here are some resources that could help you to write better Github issues in the future:
* https://wiredcraft.com/blog/how-we-write-our-github-issues/
* https://tilburgsciencehub.com/building-blocks/collaborate-and-share-your-work/project_management/write-good-issues/

And "please retrain him" thanks for making me laugh 😄
Sadly there is no such thing as "Improve" magic button, or I would spam it on regular basis.
I can retrain it 200 times the output will be the same.

**Comment by NullVerdict** [comment]
If you're too lazy to figure out your code, just say so. I don't think the way you do, and I'm just telling you my own experience.  The tinyld reacts very badly to special characters (. , # and emoji and other). I'm asking you to just add a silly filter for this stuff. It's just that when I used it without it it worked worse than your game on unity. Thanks for understanding
