### ISSUE TITLE
Indonesian's language code is not correct

### ISSUE THREAD

**Issue by Shan-Mi** [komodojp/tinyld#4]
https://github.com/komodojp/tinyld/blob/develop/docs/langs.md
language code for Indonesian is not correct.

**Comment by Shan-Mi** [comment]
sv: Swedish

**Comment by Shan-Mi** [comment]
ber: Berber

**Comment by Shan-Mi** [comment]
lt: 'Lithuanian'

**Comment by Shan-Mi** [comment]
be: 'Belarusian'

**Comment by kefniark** [comment]
Thanks for you time and your feedback.
Indeed this file seems to contain typo and errors.

I checked and those do not exist in the code
https://github.com/komodojp/tinyld/blob/develop/src/core.ts#L67

So it seems to be only a documentation issue and bad copy paste.
I will see if I cannot get this doc autogenerated from the code, it would avoid such disruptency and typo to occur
