### ISSUE TITLE
Add more languages

### ISSUE THREAD

**Issue by kefniark** [komodojp/tinyld#8]
## Description
Add more languages, the goal would be to have:
* 80~100 languages for `tinyld`
* 30~40 languages for `tinyld-light`

So far, to me it sounds a bit useless to do more than 100 languages.
It really become niche usage and the accuracy of those small languages just degrade.

**Comment by Totistar** [comment]
add Catalan (ISO Codes: ca cat) please ???

**Comment by kefniark** [comment]
I will take a look, but it's typically the kind of language I usually avoid 😄
Not in the top 100 language by speakers and really close to spanish and french, so good to create false positive with those languages on short sentences.

Another idea I need to experiment is to provide bigger profiles with more languages. And provide a way for people to recompile the library with only the 20~30 languages subset they need.

**Comment by Totistar** [comment]
It would be great to have him. We are clear about the relationship of Catalan with Spanish and French. But having 7 million speakers, similar to Danish for example. I'm sure it can be useful for many people. I encourage you.
